# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
# Files stored in repository root
  - package-ecosystem: "npm"
    directory: "/"
    commit-message:
      prefix: chore
      include: "scope"
    schedule:
      interval: "weekly"
# Workflow files stored in the default location of `.github/workflows`
  - package-ecosystem: "github-actions"
    directory: "/"
    commit-message:
      prefix: ci
      include: "scope"
    schedule:
      interval: "weekly"
